# Generated by Django 5.1.2 on 2024-11-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(default='Введите адрес', max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='facebook',
            field=models.URLField(blank=True, default='https://facebook.com/'),
        ),
        migrations.AddField(
            model_name='contact',
            name='instagram',
            field=models.URLField(blank=True, default='https://instagram.com/'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone1',
            field=models.CharField(default='+996 777 111 222', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone2',
            field=models.CharField(default='+996 555 222 333', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='kyrgyz_venture@tour.kg', max_length=254),
        ),
    ]
