# Generated by Django 5.0.4 on 2024-10-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='image_url',
        ),
        migrations.AddField(
            model_name='destination',
            name='image1',
            field=models.ImageField(blank=True, max_length=1500, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='destination',
            name='image2',
            field=models.ImageField(blank=True, max_length=1500, null=True, upload_to=''),
        ),
    ]
