# Generated by Django 5.1.2 on 2024-11-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_remove_destination_image_url_destination_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
